
package controller;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ArduinoImplService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8080/arduino?wsdl")
public class ArduinoImplService
    extends Service
{

    private final static URL ARDUINOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ARDUINOIMPLSERVICE_EXCEPTION;
    private final static QName ARDUINOIMPLSERVICE_QNAME = new QName("http://service/", "ArduinoImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/arduino?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ARDUINOIMPLSERVICE_WSDL_LOCATION = url;
        ARDUINOIMPLSERVICE_EXCEPTION = e;
    }

    public ArduinoImplService() {
        super(__getWsdlLocation(), ARDUINOIMPLSERVICE_QNAME);
    }

    public ArduinoImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ARDUINOIMPLSERVICE_QNAME, features);
    }

    public ArduinoImplService(URL wsdlLocation) {
        super(wsdlLocation, ARDUINOIMPLSERVICE_QNAME);
    }

    public ArduinoImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ARDUINOIMPLSERVICE_QNAME, features);
    }

    public ArduinoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ArduinoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Arduino
     */
    @WebEndpoint(name = "ArduinoImplPort")
    public Arduino getArduinoImplPort() {
        return super.getPort(new QName("http://service/", "ArduinoImplPort"), Arduino.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Arduino
     */
    @WebEndpoint(name = "ArduinoImplPort")
    public Arduino getArduinoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "ArduinoImplPort"), Arduino.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ARDUINOIMPLSERVICE_EXCEPTION!= null) {
            throw ARDUINOIMPLSERVICE_EXCEPTION;
        }
        return ARDUINOIMPLSERVICE_WSDL_LOCATION;
    }

}
