
package controller;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Arduino", targetNamespace = "http://interfaces/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Arduino {


    /**
     * 
     * @return
     *     returns boolean
     * @throws ArduinoServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "turnOnLED", targetNamespace = "http://interfaces/", className = "controller.TurnOnLED")
    @ResponseWrapper(localName = "turnOnLEDResponse", targetNamespace = "http://interfaces/", className = "controller.TurnOnLEDResponse")
    @Action(input = "http://interfaces/Arduino/turnOnLEDRequest", output = "http://interfaces/Arduino/turnOnLEDResponse", fault = {
        @FaultAction(className = ArduinoServiceException_Exception.class, value = "http://interfaces/Arduino/turnOnLED/Fault/ArduinoServiceException")
    })
    public boolean turnOnLED()
        throws ArduinoServiceException_Exception
    ;

    /**
     * 
     * @return
     *     returns boolean
     * @throws ArduinoServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "turnOffLED", targetNamespace = "http://interfaces/", className = "controller.TurnOffLED")
    @ResponseWrapper(localName = "turnOffLEDResponse", targetNamespace = "http://interfaces/", className = "controller.TurnOffLEDResponse")
    @Action(input = "http://interfaces/Arduino/turnOffLEDRequest", output = "http://interfaces/Arduino/turnOffLEDResponse", fault = {
        @FaultAction(className = ArduinoServiceException_Exception.class, value = "http://interfaces/Arduino/turnOffLED/Fault/ArduinoServiceException")
    })
    public boolean turnOffLED()
        throws ArduinoServiceException_Exception
    ;

}
